function [  ] = ploy3D_Gait(ds, R1, R2, R3, L1, L2, L3, useNorm )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

r1X = [R1 , '_X'];
r1Y = [R1 , '_Y'];
r1Z = [R1 , '_Z'];
r2X = [R2 , '_X'];
r2Y = [R2 , '_Y'];
r2Z = [R2 , '_Z'];
r3X = [R3 , '_X'];
r3Y = [R3 , '_Y'];
r3Z = [R3 , '_Z'];

l1X = [L1 , '_X'];
l1Y = [L1 , '_Y'];
l1Z = [L1 , '_Z'];
l2X = [L2 , '_X'];
l2Y = [L2 , '_Y'];
l2Z = [L2 , '_Z'];
l3X = [L3 , '_X'];
l3Y = [L3 , '_Y'];
l3Z = [L3 , '_Z'];

xmin = min([ds.(r1X) ; ds.(r2X) ; ds.(r3X) ; ...
    ds.(l1X) ; ds.(l2X) ; ds.(l3X)]);
xmax = max([ds.(r1X) ; ds.(r2X) ; ds.(r3X) ; ...
    ds.(l1X) ; ds.(l2X) ; ds.(l3X)]);

ymin = min([ds.(r1Y) ; ds.(r2Y) ; ds.(r3Y) ; ...
    ds.(l1Y) ; ds.(l2Y) ; ds.(l3Y)]);
ymax = max([ds.(r1Y) ; ds.(r2Y) ; ds.(r3Y) ; ...
    ds.(l1Y) ; ds.(l2Y) ; ds.(l3Y)]);

zmin = min([ds.(r1Z) ; ds.(r2Z) ; ds.(r3Z) ; ...
    ds.(l1Z) ; ds.(l2Z) ; ds.(l3Z)]);
zmax = max([ds.(r1Z) ; ds.(r2Z) ; ds.(r3Z) ; ...
    ds.(l1Z) ; ds.(l2Z) ; ds.(l3Z)]);

% useNorm = 0;

for ii = 1:height(ds)
    
    cla
    
    % RIGHT POINTS
    scatter3(ds.(r1X)(ii), ds.(r1Y)(ii), ds.(r1Z)(ii),50,'r','filled')
    hold on
    scatter3(ds.(r2X)(ii), ds.(r2Y)(ii), ds.(r2Z)(ii),50,'k','filled')
    scatter3(ds.(r3X)(ii), ds.(r3Y)(ii), ds.(r3Z)(ii),50,'b','filled')
    
    text(ds.(r1X)(ii),...
        ds.(r1Y)(ii),...
        ds.(r1Z)(ii),...
        'RWrist',...
        'Color','r',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    text(ds.(r2X)(ii),...
        ds.(r2Y)(ii),...
        ds.(r2Z)(ii),...
        'RElbow',...
        'Color','k',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    text(ds.(r3X)(ii),...
        ds.(r3Y)(ii),...
        ds.(r3Z)(ii),...
        'RShoulder',...
        'Color','b',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    RxS = [ds.(r1X)(ii) , ds.(r2X)(ii)];
    RyS = [ds.(r1Y)(ii) , ds.(r2Y)(ii)];
    RzS = [ds.(r1Z)(ii) , ds.(r2Z)(ii)];
    
    RxS2 = [ds.(r2X)(ii) , ds.(r3X)(ii)];
    RyS2 = [ds.(r2Y)(ii) , ds.(r3Y)(ii)];
    RzS2 = [ds.(r2Z)(ii) , ds.(r3Z)(ii)];
    
    % Connector
    plot3(RxS, RyS, RzS,'r')
    plot3(RxS2, RyS2, RzS2,'b')
    
    
    % LEFT POINTS
    scatter3(ds.(l1X)(ii), ds.(l1Y)(ii), ds.(l1Z)(ii),50,'r','filled')
    scatter3(ds.(l2X)(ii), ds.(l2Y)(ii), ds.(l2Z)(ii),50,'k','filled')
    scatter3(ds.(l3X)(ii), ds.(l3Y)(ii), ds.(l3Z)(ii),50,'b','filled')
    
    text(ds.(l1X)(ii),...
        ds.(l1Y)(ii),...
        ds.(l1Z)(ii),...
        'LWrist',...
        'Color','r',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    text(ds.(l2X)(ii),...
        ds.(l2Y)(ii),...
        ds.(l2Z)(ii),...
        'LElbow',...
        'Color','k',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    text(ds.(l3X)(ii),...
        ds.(l3Y)(ii),...
        ds.(l3Z)(ii),...
        'LShoulder',...
        'Color','b',...
        'VerticalAlignment','bottom',...
        'HorizontalAlignment','center',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'FontWeight','bold')
    
    LxS = [ds.(l1X)(ii) , ds.(l2X)(ii)];
    LyS = [ds.(l1Y)(ii) , ds.(l2Y)(ii)];
    LzS = [ds.(l1Z)(ii) , ds.(l2Z)(ii)];
    
    LxS2 = [ds.(l2X)(ii) , ds.(l3X)(ii)];
    LyS2 = [ds.(l2Y)(ii) , ds.(l3Y)(ii)];
    LzS2 = [ds.(l2Z)(ii) , ds.(l3Z)(ii)];
    
    % Connector
    plot3(LxS, LyS, LzS,'r')
    plot3(LxS2, LyS2, LzS2,'b')
    
    
    
    
    
    if useNorm
        
        xlim([xmin xmax]);
        ylim([ymin ymax]);
        zlim([zmin zmax]);
        
    end
    
    xlabel('X Axis')
    ylabel('Y Axis')
    zlabel('Z Axis')
    
    pause(0.001)
    
end




end

